spring.application.name=car.sale
spring.datasource.url=jdbc:mysql://localhost:3306/car_sale_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=TB20010415
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true